env:
  global:
   # TRAVIS_BRANCH is tag name if tag provided else branch name
   - XMS_VERSION: $TRAVIS_BRANCH
   - CONAN_REFERENCE: "xmdf/${XMS_VERSION}"
   - CONAN_USERNAME: "aquaveo"
   - CONAN_CHANNEL: "stable"
   - CONAN_LOGIN_USERNAME: $CONAN_USER_SECRET
   - CONAN_PASSWORD: $CONAN_PASSWORD_SECRET
   - CONAN_REMOTES: $AQUAVEO_CONAN
   - GH_REPO_NAME: xmdf
   - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen/Doxyfile
   - GH_REPO_REF: github.com/Aquaveo/xmdf.git
   - PYTHON_TARGET_VERSION: 2.7
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python:
     - 2.7
   services:
     - docker
osx: &osx
   os: osx
   language: generic

stages:
    - name: test
      if: NOT tag IS present
    - name: deploy
      if: tag =~ ^\d+\.\d+\.\d+$

# Global Lifecycle Steps
# See: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

# Install Step
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

# Build Step
script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

# After Success
after_success:
  - python test.py

# Jobs/Build Matrix
# Note: Lifecycle Steps specified in stages will override Global Lifecycle Steps
jobs:
   include:
      # --- TEST STAGE ------------------------------------------------------------------------------------------------
      - stage: test
        if: branch = master
        addons:
          apt:
            packages:
              - doxygen
              - doxygen-doc
              - doxygen-latex
              - doxygen-gui
              - graphviz
        <<: *linux
        env: TASK_NAME="DOXYGEN Generation"
        script: 
          - cd $TRAVIS_BUILD_DIR
          - chmod +x generateDocumentationAndDeploy.sh
          - ./generateDocumentationAndDeploy.sh

      # GCC 5
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # GCC 6
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # GCC 7
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # OSX
      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
 
      # --- DEPLOY STAGE ----------------------------------------------------------------------------------------------

      # GCC 5
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # GCC 6
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # GCC 7
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # OSX
      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
